### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by TheDalaiAlpaca** [G-P-L/AUR#2]
Hi, motionbox 1.6.0.4-4 from the AUR seems to fail the checksum for me.
```
:: Parsing SRCINFO (1/1): motionbox
==> Making package: motionbox 1.6.0.4-4 (do 04 jun 2020 12:05:01 CEST)
==> Retrieving sources...
  -> Found MotionBox-1.6.0-linux64.tar.gz
  -> Found MotionBox.desktop
  -> Found MotionBox.png
==> Validating source files with sha256sums...
    MotionBox-1.6.0-linux64.tar.gz ... FAILED
    MotionBox.desktop ... Passed
    MotionBox.png ... Passed
==> ERROR: One or more files did not pass the validity check!
Error downloading sources: motionbox
```

**Comment by G-P-L** [comment]
Hi!

I checked the package, but it can build without error for me. I also rechecked the checksums, but they are fine for me.

Are you using some kind of graphical manager, like pamac? If yes, maybe you have to empty the AUR cache, because an older version of the MotionBox-1.6.0-linux64.tar.gz file is causing the problem.

**Comment by TheDalaiAlpaca** [comment]
Sorry, I should've mentioned I'm using yay. I cleaned the cache with `yay -Sc --aur`, and then the package installed flawlessly. Thanks!
